ARG WORK_DIR
ARG NODE_VERSION

FROM node:$NODE_VERSION

WORKDIR $WORK_DIR

#RUN apk update && \
#    apk add --no-cache nano bash htop && \
#    npm install -g nodemon

RUN npm install -g rimraf
COPY ./package*.json ./
RUN npm install
COPY ./ ./
RUN rimraf dist
RUN npx tsc
CMD ["node", "dist/app.js"]